  #********************************************************************************
  # Copyright (c) 2025 Next Industries s.r.l.
  #
  # This program and the accompanying materials are made available under the
  # terms of the Apache 2.0 which is available at http://www.apache.org/licenses/LICENSE-2.0
  #
  # SPDX-License-Identifier: Apache-2.0
  #
  # Project Name:
  # Tactigon Soul - Shape
  # 
  # Release date: 30/09/2025
  # Release version: 1.0
  #
  # Contributors:
  # - Massimiliano Bellino
  # - Stefano Barbareschi
  #********************************************************************************/

  services:

    sunrise:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: sunrise
      restart: unless-stopped
      network_mode: host
      privileged: true
      environment:
        - ROS_DOMAIN_ID=0
        - SDL_AUDIODRIVER=dummy
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
      devices:
        - /dev:/dev
      volumes:
        - /var/run/dbus:/var/run/dbus
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ${HOME}/.Xauthority:/root/.Xauthority:rw

    tactigon-speech-socket:
      build:
        context: ./speech
        dockerfile: Dockerfile
      container_name: tactigon-speech-socket
      restart: unless-stopped
      network_mode: host
      environment:
        TSS_ADDRESS: localhost
        TSS_PORT: 50007
        TSS_CONFIG: config.json

    sunrise-comau:
      build:
        context: ./sunrise_robot
        dockerfile: Dockerfile
      container_name: sunrise-comau
      tty: true
      stdin_open: true
      network_mode: host
      environment:
        - ROS_DOMAIN_ID=0
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
        - ROBOT_MODEL=racer7-14
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ${HOME}/.Xauthority:/root/.Xauthority:rw
      restart: unless-stopped
      entrypoint: ["/entrypoint.sh"]

    sunrise-timescaledb:
      image: timescale/timescaledb:latest-pg17
      container_name: sunrise-timescaledb
      hostname: sunrise-timescaledb
      restart: always
      environment:
        - POSTGRES_USER=orion
        - POSTGRES_PASSWORD=orion
        - POSTGRES_HOST_AUTH_METHOD=trust
      networks:
        - fiware_network
      ports:
        - "5432:5432"
      command: ["postgres", "-c", "log_statement=all"]
      volumes:
        - timescale_data:/home/postgres/pgdata/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U orion"]
        interval: 15s
        timeout: 15s
        retries: 5
        start_period: 60s


    sunrise-mintaka:
      image: fiware/mintaka:0.6.18
      container_name: sunrise-mintaka
      hostname: sunrise-mintaka
      restart: always
      networks:
        - fiware_network
      ports:
        - "8080:8080"
      depends_on:
        - sunrise-timescaledb
      environment:
        - MICRONAUT_SERVER_PORT=8080
        - MICRONAUT_METRICS_ENABLED=true
        - ENDPOINTS_ALL_PORT=8080
        - ENDPOINTS_METRICS_ENABLED=true
        - ENDPOINTS_HEALTH_ENABLED=true
        - DATASOURCES_DEFAULT_HOST=sunrise-timescaledb
        - DATASOURCES_DEFAULT_PORT=5432
        - DATASOURCES_DEFAULT_USERNAME=orion
        - DATASOURCES_DEFAULT_PASSWORD=orion
        - DATASOURCES_DEFAULT_DATABASE=orion
        - LOGGERS_LEVEL_ROOT=TRACE

    sunrise-grafana:
      image: grafana/grafana:latest
      container_name: sunrise-grafana
      restart: always
      ports:
        - "3000:3000"
      networks:
        - fiware_network
      depends_on:
        - sunrise-mintaka
      environment:
        - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/datasources:/etc/grafana/provisioning/datasources
        - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
        - ./grafana/dashboards:/var/lib/grafana/dashboards_json

    mongodb:
      image: mongo:4.4
      container_name: fiware-mongodb
      hostname: mongodb
      networks:
        - fiware_network
      ports:
        - "27017:27017"
      command: --bind_ip_all
      volumes:
        - mongodb_data:/data/db

    # FIWARE Orion-LD Context Broker
    fiware-orion:
      image: fiware/orion-ld:latest
      container_name: fiware-orion
      hostname: orion
      depends_on:
        - mongodb
        - sunrise-timescaledb
      networks:
        - fiware_network
      ports:
        - "1026:1026"
      command: -dbhost mongodb -logLevel DEBUG # -t 0-255 -kt 0-2000
      environment:
        - ORIONLD_TROE=TRUE
        - ORIONLD_TROE_HOST=sunrise-timescaledb
        - ORIONLD_TROE_PORT=5432
        - ORIONLD_TROE_USER=orion
        - ORIONLD_TROE_PWD=orion
        - ORIONLD_MONGO_HOST=mongodb
      healthcheck:
        test: curl --fail -s http://localhost:1026/version || exit 1
        interval: 30s
        retries: 15

    # Integration Service con Dynamic ROS2 e FIWARE System Handles
    integration-service:
      build:
        context: .
        dockerfile: sunrise_fiware/Dockerfile
      container_name: integration-service
      depends_on:
        fiware-orion:
          condition: service_healthy
      # networks:
      #   - fiware_network

      network_mode: host
      volumes:
        - ./config:/config
        - is_workspace:/is_ws
      environment:
        - ROS_DOMAIN_ID=0
        - FIWARE_HOST=localhost
        - FIWARE_PORT=1026
      stdin_open: true
      tty: true
      restart: unless-stopped
      #command: bash -c "tail -f /dev/null"
      # command: >
      #   bash -c '
      #   source /opt/vulcanexus/humble/setup.bash &&
      #   integration-service /config/integration_service.yaml
      #   '
      #entrypoint: ["/bin/bash"]          # ← sovrascrive il ros2_entrypoint.sh
      command: integration-service /config/integration_service.yaml

  networks:
    fiware_network:
      driver: bridge


  volumes:
    timescale_data:
    grafana_data:
    mongodb_data:
      driver: local
    is_workspace:
      driver: local