{
 "title": "Sunrise Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Product Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sunrise_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  valore AS \"Quantità Totale\",\n  nome_metrica AS metric\nFROM telemetria_robot\nWHERE\n  nome_metrica IN ('ventilator_manufactured') AND\n  $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "dataset": "sunrise_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  valore AS \"Quantità\",\n  nome_metrica AS metric\nFROM telemetria_robot\nWHERE\n  nome_metrica IN ('defect_ventilator') AND\n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Defect Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5s', time) AS \"time\",\n  100 - ((MAX(valore) FILTER (WHERE nome_metrica = 'defect_ventilator') / \n   NULLIF(MAX(valore) FILTER (WHERE nome_metrica = 'ventilator_manufactured'), 0)) * 100) AS \"Pezzi Sani (%)\"\nFROM telemetria_robot\nWHERE\n  nome_metrica IN ('defect_ventilator', 'ventilator_manufactured') AND\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Job Time Efficency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  valore AS \"Setup Time (s)\"\nFROM telemetria_robot\nWHERE nome_metrica = 'setup_time' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "dataset": "sunrise_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  valore AS \"Downtime (s)\"\nFROM telemetria_robot\nWHERE nome_metrica = 'downtime' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "dataset": "sunrise_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  valore AS \"Time to recall DB (s)\"\nFROM telemetria_robot\nWHERE nome_metrica = 'time_to_recall_db' AND $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sunrise_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  valore AS \"Job Accuracy (%)\"\nFROM telemetria_robot\nWHERE nome_metrica = 'job_accuracy' AND $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  }
 ]
}