systems:
  ros2:
    type: ros2_dynamic
  fiware:
    type: fiware
    host: 127.0.0.1
    port: 1026

routes:
  ros2_to_fiware: { from: ros2, to: fiware }

topics:
  /hello_fiware:
    type: "std_msgs/msg/String"
    route: ros2_to_fiware

  /sunrise_app/bridge/intent:
    type: "sunrise_msgs/msg/Intent"
    route: ros2_to_fiware

  /sunrise_app/bridge/action:
    type: "sunrise_msgs/msg/Action"
    route: ros2_to_fiware

  /camera_tracking/pointing:
    type: "sunrise_msgs/msg/Marker"
    route: ros2_to_fiware

  /human/body/person1/gesture:
    type: "sunrise_msgs/msg/Gesture"
    route: ros2_to_fiware

  /human/voices/person1/livespeech:
    type: "sunrise_msgs/msg/Transcription"
    route: ros2_to_fiware