uint32 code
string[] error_msg

string ERR_TCP_UNDEFINED=Error not defined
string ERR_TCP_CONN_STATE=State server connection failed    
string ERR_TCP_CONN_ROBOT=Robot server connection failed 
string ERR_TCP_CONN_ARM=Arm server connection failed
string ERR_TCP_READ=State server TCP/IP write failed  
string ERR_TCP_WRITE_CMD=Robot server TCP/IP read failed
string ERR_TCP_WRITE_MOTION=Arm server TCP/IP read failed
string ERR_TCP_DISCONN_STATE=State server disconnection failed
string ERR_TCP_DISCONN_ROBOT=Robot server disconnection failed
string ERR_TCP_DISCONN_ARM=Arm server disconnection failed
string ERR_SAFETY_GATE=Safety gate / Emergency stop error
string ERR_WRONG_MOTION=Program Execution Errors (36864-37191)
string ERR_ALARM=Active Alarm at Restarting. Please press rset button
string ERR_MOTION_DRIVEOFF=Trajectory sent in not correct state (Drive-on and start necessary). Please press reset button.