#********************************************************************************
# Copyright (c) 2025 Next Industries s.r.l.
#
# This program and the accompanying materials are made available under the
# terms of the Apache 2.0 which is available at http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
# Massimiliano Bellino
# Stefano Barbareschi
#********************************************************************************/

# Enum-like constants
int8 GESTURE = 0
int8 VOICE_COMMAND = 1
int8 TOUCH = 2
int8 CAMERA_POINT = 3

# Fields
int8 type
string payload